### ISSUE TITLE
Given a Calendar object, converting it to String and back

### ISSUE THREAD

**Issue by kevinLamKB** [CS2103JUN2017-T2/main#105]
import java.text.SimpleDateFormat;

SimpleDateFormat sdf = new SimpleDateFormat("d/M/y H:mm");
sdf.setLenient(false);

String toStore = sdf.format(calendar.getTime());

to convert back from string to Calendar use
calendar.setTime(sdf.parse(toStore));

https://www3.ntu.edu.sg/home/ehchua/programming/java/DateTimeCalendar.html

**Comment by akd13** [comment]
Fixed in storage.
