### ISSUE TITLE
Modify Model Architecture for V0.4

### ISSUE THREAD

**Issue by ChuaPingChan** [CS2103JUN2017-T2/main#111]
![modelclassdiagramv0 4](https://user-images.githubusercontent.com/29548741/28023250-ec1d0f92-65bf-11e7-803c-0177e91c71e4.png)

Things to change:
* Add `State` field to entries.
  * `State` is not required by constructor. Constructor instantiates entries in active state by default. Clients can change state of entries with setter methods.
  * `State` *is* used to determine duplicate entries.
  * Implement a `toString()` method for `State` for easy conversion to XML format.
  * Run through all methods of `EntryBook` to see if setting States are necessary.
* `EventList`, `DeadlineList` and `FloatingTaskList` now contains entries of all states (i.e. active, deleted, archived). `EntryBook` should now have methods that:
  * Change the states of entries.
* Allow duplicated floating tasks to be added if the existing floating task is in the deleted or archived state. When this happens, set the state of the floating task back to active.
* Modify filtered list predicates to match entries' state, in addition to name and tag keywords.

**Comment by ChuaPingChan** [comment]
@kevinLamKB 
Regarding this new architecture, I'm wondering if you're okay if Logic needs to provide an additional `State` argument to the `EntryUtil` constructor? Doing this will allow Logic to have control over what `State` the entries it instantiates.

**Comment by akd13** [comment]
@ChuaPingChan  Will need to modify storage as well - will State only contain a string or additional attributes also? Ideally a simple string stating the state (archive, active, bin) would be easiest to store

**Comment by kevinLamKB** [comment]
@ChuaPingChan i wasn't the one who updated `EntryUtil`. although for testing purposes i guess it would be easier to have that `State` argument in it

**Comment by ChuaPingChan** [comment]
@akd13 Noted, I'll implement a `toString()` for the State enum and keep you updated.

**Comment by ChuaPingChan** [comment]
Reference to #175
