### ISSUE TITLE
Feature Suggestion: Allow Edit to Change Entry between Event/Deadline/FloatingTask

### ISSUE THREAD

**Issue by akd13** [CS2103JUN2017-T2/main#162]

**Comment by kevinLamKB** [comment]
adding extra dates to entries without date half done.
currently does a model.updateEntry((Floating) oldEntry, (Deadline) editedEntry), need model side to check instance of and process accordingly from there.

**Comment by kevinLamKB** [comment]
some more parsing work for removing dates from entries, currently being caught as an exception by prettytime if parsing empty string
