### ISSUE TITLE
Nice to have : Implement config stuff

### ISSUE THREAD

**Issue by kevinLamKB** [CS2103JUN2017-T2/main#169]
have yet to set up config variables like NUM_TIMES, END_DATE_TIME , ADD_DURATION_HOURS (see userguide, ctrl f config or default) and logic flow to make use of it.

**Comment by akd13** [comment]
Sorry I'm a little confused as to what this is for? Is it for default values?

**Comment by kevinLamKB** [comment]
@akd13 ah yes, i was refering to the default values. 
basically need to add in addDurationHours (or some other better name) for the cases where user only inputs event start date but not end date.
The other 2, num_times & end_date_time were to support for recurring events i think, that one is a little far from full implementation right now.
