### ISSUE TITLE
Make GUI Display Changes when Entries are Changed with updateEntry() Method

### ISSUE THREAD

**Issue by ChuaPingChan** [CS2103JUN2017-T2/main#191]
Possible solutions:
* Implement observable properties in the `Entry` class. `EntryCard` can then bind its text labels to those observable properties.
* Make a variable in `ModelManager` that stores the last Predicate used, which can be used to 'refresh' the GUI panel once an entry is edited successfully.

**Comment by kevinLamKB** [comment]
Solved by implementing prevSearch
