### ISSUE TITLE
50 sample entries when opening 

### ISSUE THREAD

**Issue by kevinLamKB** [CS2103JUN2017-T2/main#215]

**Comment by ChuaPingChan** [comment]
Additional things to note
* Even distribution of events/deadlines/floating tasks
* Some entries with different states

**Comment by akd13** [comment]
Add more entries to sample, equally distributed between events, floating tasks, deadlines
Archived/Active/Bin
Add overlapping tasks (beginning), overdue tasks, etc
Name them appropriately
Make sure they're somewhat unique
