### ISSUE TITLE
Command that results in duplicate shouldn't create new snapshots for undo.

### ISSUE THREAD

**Issue by ChuaPingChan** [CS2103JUN2017-T2/main#239]

**Comment by akd13** [comment]
Just remove finally { indicateEntryBookChanged()} on line 114. Snapshots are only created when the indicateEntryBookChanged() event is raised

**Comment by ChuaPingChan** [comment]
@akd13 
Noted with thanks, I'll fix that later. Will need to make a bit more modification than just removing line 114 because other cases (e.g. `OverlappingEventException`) will still require `indicateEntryBookChanged()` to be executed.
