### ISSUE TITLE
Fix delete command multiple keyword search

### ISSUE THREAD

**Issue by mattheuslee** [CS2103JUN2017-T2/main#39]

**Comment by ChuaPingChan** [comment]
I realised the reason the AND-search is not working may be because the getFilteredFloatingTaskList() of the model component is doing an OR-filter. I'll check and get back to you.

**Comment by kevinLamKB** [comment]
yes, my FindCommand calls updateFilteredFloatingTaskList(keywords)

**Comment by kevinLamKB** [comment]
Fixed! well done

**Comment by ChuaPingChan** [comment]
Sorry it's not working well yet..

**Comment by ChuaPingChan** [comment]
@CS2103JUN2017-T2/developers 
I'll need some time to read up on lambda expressions and on the Predicate interface for this.

**Comment by ChuaPingChan** [comment]
Fixed by #62. Closing issue.
