### ISSUE TITLE
Add duplicate check before adding & editing task

### ISSUE THREAD

**Issue by mattheuslee** [CS2103JUN2017-T2/main#40]

**Comment by ChuaPingChan** [comment]
@CS2103JUN2017-T2/developers 
What do you all think of this? If we don't want to allow duplicates of *exact* same tasks (i.e. *every* fields are the same), everyone will need to go back to the original addressbook4 code, look for all the duplicate checks that were originally present in their components and re-introduced them into MultiTasky.

**Comment by mattheuslee** [comment]
part of https://github.com/CS2103JUN2017-T2/main/issues/113
