### ISSUE TITLE
Collate contributions to UserGuide.adoc and DeveloperGuide.adoc

### ISSUE THREAD

**Issue by mattheuslee** [CS2103JUN2017-T2/main#44]

**Comment by ChuaPingChan** [comment]
@kevinLamKB 
The collate markers are not displaying correctly when viewed on GitHub. Try using `//` and see.

**Comment by kevinLamKB** [comment]
which one? for user / developer guide?

**Comment by ChuaPingChan** [comment]
The User Guide of the branch `V0.2_kevin`.

**Comment by kevinLamKB** [comment]
haha i thought so. thanks for letting me know

**Comment by mattheuslee** [comment]
Has everyone done this for their own portions?

**Comment by akd13** [comment]
@mattheuslee Yes! Sorry I forgot to push, I've done it now!

**Comment by kevinLamKB** [comment]
@mattheuslee your matric number is A0125586X yes? i'm tagging u to user guide delete format, it was empty.

**Comment by mattheuslee** [comment]
@kevinLamKB yup it is. I must've missed out that one. thanks!

**Comment by kevinLamKB** [comment]
Alright, i've checked through to make sure no one missed out portions they've written. all good on that, closing this issue.
