### ISSUE TITLE
Implement date/time sort for list of events and deadlines

### ISSUE THREAD

**Issue by mattheuslee** [CS2103JUN2017-T2/main#45]

**Comment by akd13** [comment]
@mattheuslee might be hard to implement for V0.3. Can we shift this to V0.4 for now?

**Comment by mattheuslee** [comment]
part of https://github.com/CS2103JUN2017-T2/main/issues/114

**Comment by mattheuslee** [comment]
part of https://github.com/CS2103JUN2017-T2/main/issues/117
