### ISSUE TITLE
Implement entrybook.xml "snapshot" save and restore functionality.

### ISSUE THREAD

**Issue by mattheuslee** [CS2103JUN2017-T2/main#46]

**Comment by akd13** [comment]
@mattheuslee  can I verify with you what "snapshot" save means?

**Comment by mattheuslee** [comment]
@akd13 The general idea is this (feel free to change things if it'll work better/easier to implement):
Inside the /data folder, besides the entrybook.xml we also have a /snapshots folder. This folder stores previous versions of entrybook.xml, all the way back to the beginning.
So for example if I execute an add command, since it is mutating the model the current entrybook.xml will be moved to /snapshots, and a new entrybook.xml is created in /data for the latest state of the model.
This way, if we want to execute an undo command it means taking the latest entrybook.xml from /snapshots and using that to replace our current working entrybook.xml. The opposite applies for redo.
