### ISSUE TITLE
Implement "find" command

### ISSUE THREAD

**Issue by mattheuslee** [CS2103JUN2017-T2/main#47]

**Comment by kevinLamKB** [comment]
there is a find command already, unless this issue is talking about the bug in the searching by 'AND' keywords

**Comment by mattheuslee** [comment]
I put this here for the rest of the find command functionality, like searching the archive/bin

**Comment by kevinLamKB** [comment]
ah, i see. yes that is an issue.

**Comment by mattheuslee** [comment]
part of https://github.com/CS2103JUN2017-T2/main/issues/114
