### ISSUE TITLE
Try to refactor AND-searching into logic to improve cohesion

### ISSUE THREAD

**Issue by kevinLamKB** [CS2103JUN2017-T2/main#59]
note to self: look at updateFilteredFloatingTaskList

**Comment by mattheuslee** [comment]
Is this complete yet? If not let's shift it to V0.3

**Comment by kevinLamKB** [comment]
Not yet, i think i want to focus on the test cases first. moving to V0.3

**Comment by ChuaPingChan** [comment]
Actually letting model add APIs for both AND-filter and OR-filter would be more cohesive right, what do you think? @kevinLamKB 

We don't need an OR-filter now, but other clients that want an OR-search can just use the same Model component.

**Comment by kevinLamKB** [comment]
sounds good, should be easy enough to implement using the original search methods

**Comment by ChuaPingChan** [comment]
👍 yeah. If so then this issue can be closed already.

**Comment by kevinLamKB** [comment]
👍
