### ISSUE TITLE
Allow _ in task names / tags [optional]

### ISSUE THREAD

**Issue by kevinLamKB** [CS2103JUN2017-T2/main#63]
to accomodate for tags with multiple words

**Comment by ChuaPingChan** [comment]
@kevinLamKB 
👍 I can do this for tags the same way I did for Names

**Comment by kevinLamKB** [comment]
Ok thanks , i noticed this problem because putting spaces for example /tag long tag name creates 3 different tags 'long' 'tag' and 'name' instead of one single tag. allowing an underscore would help with that problem.
