### ISSUE TITLE
List events automatically after deleting by keyword instead of current blank display

### ISSUE THREAD

**Issue by mattheuslee** [CS2103JUN2017-T2/main#65]

**Comment by kevinLamKB** [comment]
same issue with edit command, it is doing a list all instead of list previous

**Comment by kevinLamKB** [comment]
okay i looked through the code, i can fix the main issue by adding one line.
lemme dig through a bit more for the edit problem

**Comment by ChuaPingChan** [comment]
@kevinLamKB 
Seems like this problem happens only when we delete with keyword. Deletion with '/float' marker updates the display of the latest filteredList just fine. Can you briefly tell us how that one works?

**Comment by kevinLamKB** [comment]
so in deletion by /float, i can use the list that i take from getFilteredFloatingTaskList.
with that list i can easily reach the Entry that i want to delete and then pass it to model to delete.

the key difference is that the other deletion by keyword, the 'found list' and the 'current list' can be completely different, so theres no way to always reach the entryToDelete using getFilteredFloatingTaskList, unless i do a search with the new keywords.

**Comment by ChuaPingChan** [comment]
Hmm I see. One realisation I have is that Jim may use `delete` or `edit` on an entry that isn't displayed in the filtered list. Something like

> What Jim types `list`:
> 1. homework 1
> 2. cs2103 lecture
> 3. homework 2
> 
> Jim do `find homework`. MultiTasky will display:
> 1. homework 1
> 2. homework 2
> 
> Jim then do this `delete lecture`

In such case, it doesn't really make sense to try to refresh the filtered list, because the deleted or edited entry isn't shown in the list he sees before using `delete` or `edit`. Right?

**Comment by kevinLamKB** [comment]
erm sorry, i don't get what u mean by refresh the list with 1 entry less. So ideally it should still show 

1. homework1
2. homework2

after jim does his `delete lecture` , is that what u meant?

**Comment by ChuaPingChan** [comment]
Hmm, yes I guess still showing
> 1. homework 1
> 2. homework 2

would be fine.

It's okay ignore my previous message haha, it's invalid.

**Comment by ChuaPingChan** [comment]
I think I get what you mean now. I have a few more questions that I need to clarify about the workings inside Logic, but it'll be lengthy. Since this is of low priority and is too dependent on the other developments, maybe we discuss this only on Monday?

**Comment by kevinLamKB** [comment]
Haha, sorry if i'm being unclear. I agree, this issue is not that pressing, lets discuss more on Monday. Maybe i'll be able to understand more of how Model works also and then find a nice solution.

**Comment by mattheuslee** [comment]
part of https://github.com/CS2103JUN2017-T2/main/issues/114
