### ISSUE TITLE
Fix edit command needing to do a list all entries after edits

### ISSUE THREAD

**Issue by kevinLamKB** [CS2103JUN2017-T2/main#66]
currently : after editting NAME of an entry, it disappears from the currently shown list on the UI.
ideally : list remains the same as previous, so that user can compare the changes he made directly

**Comment by kevinLamKB** [comment]
subsidiary problem : edit by keyword search, when only 1 task is found , edits it. But app shows an empty screen currently. ideally, show the editted entry.

**Comment by ChuaPingChan** [comment]
![image](https://user-images.githubusercontent.com/29548741/28001479-5a292702-655f-11e7-9577-585dd45067a7.png)
Can this be the solution? @kevinLamKB @mattheuslee

**Comment by kevinLamKB** [comment]
I'm not sure if this will fix this edit problem, i think the issue is more of how the filteredEntries FilteredList in ModelManager currently works. 
cos it currently filters the full list by some predicate (search through name and tag whether they contain some keywords). so if for example the name and tag of an entry is edited and they no longer fall under the predicate, then they will be filtered out from filteredEntries, which is why the edited entry disappears from the user's previously shown list.

**Comment by ChuaPingChan** [comment]
I think I sort of understand how it works and have an idea of a possible solution now, I'll tell you all about it when we meet tomorrow.

**Comment by kevinLamKB** [comment]
👍

**Comment by mattheuslee** [comment]
part of https://github.com/CS2103JUN2017-T2/main/issues/115
