### ISSUE TITLE
Find using non-alphanumeric characters

### ISSUE THREAD

**Issue by ChuaPingChan** [CS2103JUN2017-T2/main#78]
Now that name and tags allow non-alphanumeric characters, wecan consider allowing user to search using non-alphanumeric character within their keyword. Just a suggestion, it's not actually that useful because I don't think most people would search for entries using symbols.

**Comment by mattheuslee** [comment]
This feature seems to be working for me though. I can `add task$` followed by `find $` which brings up that task.

**Comment by ChuaPingChan** [comment]
Cool, okay. Can you help to add some test cases with a few more other symbols in the GUI system test too? e.g. `?`, `*`. If they all work fine after we merge our branches and make it compile for V0.3 then maybe we can close this issue already. Thanks!

**Comment by mattheuslee** [comment]
part of https://github.com/CS2103JUN2017-T2/main/issues/114
