### ISSUE TITLE
Implement the 'OR' find 

### ISSUE THREAD

**Issue by kevinLamKB** [CS2103JUN2017-T2/main#81]
suggested flag: /or , can be used after or before keywords to use OR finding for every keyword
e.g.
find /or CS2103 lecture at school, 
find CS2103 lecture at school /or
will do a CS2103 OR lecture OR at OR school search.

next step:
higher level implementation: allow /or anywhere
find CS2103 lecture /or at school
does a CS2103 AND lecture OR at AND school search

**Comment by mattheuslee** [comment]
part of https://github.com/CS2103JUN2017-T2/main/issues/114

**Comment by ChuaPingChan** [comment]
Part of #199
