### ISSUE TITLE
Set file storage to be in a specific directory

### ISSUE THREAD

**Issue by akd13** [CS2103JUN2017-T2/main#86]

**Comment by mattheuslee** [comment]
part of https://github.com/CS2103JUN2017-T2/main/issues/120

**Comment by mattheuslee** [comment]
@CS2103JUN2017-T2/developers Does this issue mean that the command to change the directory should be implemented?

**Comment by akd13** [comment]
@mattheuslee I suppose so. @CS2103JUN2017-T2/developers I was thinking we add a *set* command to the user guide to set the file path. Something like - set /Users/usernamehere/Desktop . If the directory exists then it starts storing the files there, and if it doesn't exist then it asks the user to input a proper file path. What dy'all think?
